services:
  webots:
    image: cyberbotics/webots:R2025a-ubuntu22.04
    container_name: webots
    network_mode: host
    privileged: true
    
    environment:
      - DISPLAY=${DISPLAY}
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./projects:/root/projects
    
    stdin_open: true
    tty: true
    
    command: webots
