version: '3.8'

services:
  webots:
    image: cyberbotics/webots:R2023b-ubuntu22.04
    container_name: webots
    platform: linux/arm64/v8
    
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
    
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./projects:/root/projects
    
    stdin_open: true
    tty: true
    
    command: webots --minimize --no-rendering
